// <auto-generated />
using Api.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329220000_FixNullEliminatedContestantIds")]
    partial class FixNullEliminatedContestantIds
    {
    }
}
