// <auto-generated />
using Api.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329210000_MultipleEliminationsPerEpisode")]
    partial class MultipleEliminationsPerEpisode
    {
    }
}
