/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * De Mol API
 * OpenAPI spec version: v1
 */
import { fetcher } from './fetcher'
export interface Contestant {
  id?: string
  name?: string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  age?: number | string
  photoUrl?: string
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  eliminatedInEpisode?: number | string | null
}

export interface AddContestantsRequest {
  /** @nullable */
  contestants: Contestant[] | null
}

export interface AdminUserResponse {
  id: string
  email: string
  displayName: string
  isAdmin: boolean
}

export interface AppConfig {
  passwordlessApiKey: string
}

export interface CreateEpisodeRequest {
  deadline: string
  /** @nullable */
  eliminatedContestantId: string | null
}

export interface CreateGameRequest {
  /** @nullable */
  name: string | null
  /** @nullable */
  contestants: Contestant[] | null
}

export interface Episode {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  number?: number | string
  deadline?: string
  /** @nullable */
  eliminatedContestantId?: string | null
}

export interface EpisodeScore {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  episodeNumber?: number | string
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  score?: number | string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rankGiven?: number | string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalContestants?: number | string
}

export interface Game {
  id?: string
  name?: string
  adminUserId?: string
  contestants?: Contestant[]
  episodes?: Episode[]
  /** @nullable */
  moleContestantId?: string | null
  inviteCode?: string
}

export interface GameSummaryResponse {
  id: string
  name: string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  contestantCount: number | string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  episodeCount: number | string
}

export interface JoinGameRequest {
  /** @nullable */
  inviteCode: string | null
}

export interface LeaderboardEntry {
  userId?: string
  displayName?: string
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  totalScore?: number | string
  episodeScores?: EpisodeScore[]
}

export interface MessageResponse {
  message: string
}

export interface Ranking {
  id?: string
  gameId?: string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  episodeNumber?: number | string
  userId?: string
  contestantIds?: string[]
  submittedAt?: string
}

export interface RecoverRequest {
  email: string
}

export interface RegisterRequest {
  email: string
  displayName: string
  /** @nullable */
  inviteCode: string | null
}

export interface RegisterTokenResponse {
  token: string
}

export interface RevealMoleRequest {
  /** @nullable */
  moleContestantId: string | null
}

export interface RevealMoleResponse {
  message: string
  moleContestantId: string
}

export interface SubmitRankingRequest {
  /** @nullable */
  contestantIds: string[] | null
}

export interface UpdateEpisodeRequest {
  /** @nullable */
  deadline: string | null
  /** @nullable */
  eliminatedContestantId: string | null
}

export interface UserInfo {
  userId: string
  displayName: string
  roles: string[]
}

export interface VerifyRequest {
  token: string
}

export type registerPasskeyResponse200 = {
  data: RegisterTokenResponse
  status: 200
}

export type registerPasskeyResponseSuccess = registerPasskeyResponse200 & {
  headers: Headers
}
export type registerPasskeyResponse = registerPasskeyResponseSuccess

export const getRegisterPasskeyUrl = () => {
  return `/api/auth/register`
}

export const registerPasskey = async (
  registerRequest: RegisterRequest,
  options?: RequestInit,
): Promise<registerPasskeyResponse> => {
  return fetcher<registerPasskeyResponse>(getRegisterPasskeyUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerRequest),
  })
}

export type verifyPasskeyResponse200 = {
  data: UserInfo
  status: 200
}

export type verifyPasskeyResponseSuccess = verifyPasskeyResponse200 & {
  headers: Headers
}
export type verifyPasskeyResponse = verifyPasskeyResponseSuccess

export const getVerifyPasskeyUrl = () => {
  return `/api/auth/verify`
}

export const verifyPasskey = async (
  verifyRequest: VerifyRequest,
  options?: RequestInit,
): Promise<verifyPasskeyResponse> => {
  return fetcher<verifyPasskeyResponse>(getVerifyPasskeyUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(verifyRequest),
  })
}

export type requestRecoveryResponse200 = {
  data: MessageResponse
  status: 200
}

export type requestRecoveryResponseSuccess = requestRecoveryResponse200 & {
  headers: Headers
}
export type requestRecoveryResponse = requestRecoveryResponseSuccess

export const getRequestRecoveryUrl = () => {
  return `/api/auth/recover`
}

export const requestRecovery = async (
  recoverRequest: RecoverRequest,
  options?: RequestInit,
): Promise<requestRecoveryResponse> => {
  return fetcher<requestRecoveryResponse>(getRequestRecoveryUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(recoverRequest),
  })
}

export type logoutResponse200 = {
  data: void
  status: 200
}

export type logoutResponseSuccess = logoutResponse200 & {
  headers: Headers
}
export type logoutResponse = logoutResponseSuccess

export const getLogoutUrl = () => {
  return `/api/auth/logout`
}

export const logout = async (options?: RequestInit): Promise<logoutResponse> => {
  return fetcher<logoutResponse>(getLogoutUrl(), {
    ...options,
    method: 'GET',
  })
}

export type getMeResponse200 = {
  data: UserInfo
  status: 200
}

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers
}
export type getMeResponse = getMeResponseSuccess

export const getGetMeUrl = () => {
  return `/api/me`
}

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return fetcher<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: 'GET',
  })
}

export type createGameResponse200 = {
  data: Game
  status: 200
}

export type createGameResponseSuccess = createGameResponse200 & {
  headers: Headers
}
export type createGameResponse = createGameResponseSuccess

export const getCreateGameUrl = () => {
  return `/api/games`
}

export const createGame = async (
  createGameRequest: CreateGameRequest,
  options?: RequestInit,
): Promise<createGameResponse> => {
  return fetcher<createGameResponse>(getCreateGameUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createGameRequest),
  })
}

export type getGameResponse200 = {
  data: Game
  status: 200
}

export type getGameResponseSuccess = getGameResponse200 & {
  headers: Headers
}
export type getGameResponse = getGameResponseSuccess

export const getGetGameUrl = (gameId: string) => {
  return `/api/games/${gameId}`
}

export const getGame = async (gameId: string, options?: RequestInit): Promise<getGameResponse> => {
  return fetcher<getGameResponse>(getGetGameUrl(gameId), {
    ...options,
    method: 'GET',
  })
}

export type joinGameResponse200 = {
  data: MessageResponse
  status: 200
}

export type joinGameResponseSuccess = joinGameResponse200 & {
  headers: Headers
}
export type joinGameResponse = joinGameResponseSuccess

export const getJoinGameUrl = (gameId: string) => {
  return `/api/games/${gameId}/join`
}

export const joinGame = async (
  gameId: string,
  joinGameRequest: JoinGameRequest,
  options?: RequestInit,
): Promise<joinGameResponse> => {
  return fetcher<joinGameResponse>(getJoinGameUrl(gameId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(joinGameRequest),
  })
}

export type getGameByInviteResponse200 = {
  data: GameSummaryResponse
  status: 200
}

export type getGameByInviteResponseSuccess = getGameByInviteResponse200 & {
  headers: Headers
}
export type getGameByInviteResponse = getGameByInviteResponseSuccess

export const getGetGameByInviteUrl = (inviteCode: string) => {
  return `/api/games/by-invite/${inviteCode}`
}

export const getGameByInvite = async (
  inviteCode: string,
  options?: RequestInit,
): Promise<getGameByInviteResponse> => {
  return fetcher<getGameByInviteResponse>(getGetGameByInviteUrl(inviteCode), {
    ...options,
    method: 'GET',
  })
}

export type getMyGamesResponse200 = {
  data: Game[]
  status: 200
}

export type getMyGamesResponseSuccess = getMyGamesResponse200 & {
  headers: Headers
}
export type getMyGamesResponse = getMyGamesResponseSuccess

export const getGetMyGamesUrl = () => {
  return `/api/my-games`
}

export const getMyGames = async (options?: RequestInit): Promise<getMyGamesResponse> => {
  return fetcher<getMyGamesResponse>(getGetMyGamesUrl(), {
    ...options,
    method: 'GET',
  })
}

export type addContestantsResponse200 = {
  data: Game
  status: 200
}

export type addContestantsResponseSuccess = addContestantsResponse200 & {
  headers: Headers
}
export type addContestantsResponse = addContestantsResponseSuccess

export const getAddContestantsUrl = (gameId: string) => {
  return `/api/games/${gameId}/contestants`
}

export const addContestants = async (
  gameId: string,
  addContestantsRequest: AddContestantsRequest,
  options?: RequestInit,
): Promise<addContestantsResponse> => {
  return fetcher<addContestantsResponse>(getAddContestantsUrl(gameId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addContestantsRequest),
  })
}

export type createEpisodeResponse200 = {
  data: Episode
  status: 200
}

export type createEpisodeResponseSuccess = createEpisodeResponse200 & {
  headers: Headers
}
export type createEpisodeResponse = createEpisodeResponseSuccess

export const getCreateEpisodeUrl = (gameId: string) => {
  return `/api/games/${gameId}/episodes`
}

export const createEpisode = async (
  gameId: string,
  createEpisodeRequest: CreateEpisodeRequest,
  options?: RequestInit,
): Promise<createEpisodeResponse> => {
  return fetcher<createEpisodeResponse>(getCreateEpisodeUrl(gameId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createEpisodeRequest),
  })
}

export type updateEpisodeResponse200 = {
  data: Episode
  status: 200
}

export type updateEpisodeResponseSuccess = updateEpisodeResponse200 & {
  headers: Headers
}
export type updateEpisodeResponse = updateEpisodeResponseSuccess

export const getUpdateEpisodeUrl = (gameId: string, episodeNumber: number) => {
  return `/api/games/${gameId}/episodes/${episodeNumber}`
}

export const updateEpisode = async (
  gameId: string,
  episodeNumber: number,
  updateEpisodeRequest: UpdateEpisodeRequest,
  options?: RequestInit,
): Promise<updateEpisodeResponse> => {
  return fetcher<updateEpisodeResponse>(getUpdateEpisodeUrl(gameId, episodeNumber), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateEpisodeRequest),
  })
}

export type revealMoleResponse200 = {
  data: RevealMoleResponse
  status: 200
}

export type revealMoleResponseSuccess = revealMoleResponse200 & {
  headers: Headers
}
export type revealMoleResponse = revealMoleResponseSuccess

export const getRevealMoleUrl = (gameId: string) => {
  return `/api/games/${gameId}/reveal-mole`
}

export const revealMole = async (
  gameId: string,
  revealMoleRequest: RevealMoleRequest,
  options?: RequestInit,
): Promise<revealMoleResponse> => {
  return fetcher<revealMoleResponse>(getRevealMoleUrl(gameId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(revealMoleRequest),
  })
}

export type submitRankingResponse200 = {
  data: Ranking
  status: 200
}

export type submitRankingResponseSuccess = submitRankingResponse200 & {
  headers: Headers
}
export type submitRankingResponse = submitRankingResponseSuccess

export const getSubmitRankingUrl = (gameId: string, episodeNumber: number) => {
  return `/api/games/${gameId}/episodes/${episodeNumber}/rankings`
}

export const submitRanking = async (
  gameId: string,
  episodeNumber: number,
  submitRankingRequest: SubmitRankingRequest,
  options?: RequestInit,
): Promise<submitRankingResponse> => {
  return fetcher<submitRankingResponse>(getSubmitRankingUrl(gameId, episodeNumber), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(submitRankingRequest),
  })
}

export type getMyRankingResponse200 = {
  data: Ranking
  status: 200
}

export type getMyRankingResponseSuccess = getMyRankingResponse200 & {
  headers: Headers
}
export type getMyRankingResponse = getMyRankingResponseSuccess

export const getGetMyRankingUrl = (gameId: string, episodeNumber: number) => {
  return `/api/games/${gameId}/episodes/${episodeNumber}/rankings/mine`
}

export const getMyRanking = async (
  gameId: string,
  episodeNumber: number,
  options?: RequestInit,
): Promise<getMyRankingResponse> => {
  return fetcher<getMyRankingResponse>(getGetMyRankingUrl(gameId, episodeNumber), {
    ...options,
    method: 'GET',
  })
}

export type getMyRankingsResponse200 = {
  data: Ranking[]
  status: 200
}

export type getMyRankingsResponseSuccess = getMyRankingsResponse200 & {
  headers: Headers
}
export type getMyRankingsResponse = getMyRankingsResponseSuccess

export const getGetMyRankingsUrl = (gameId: string) => {
  return `/api/games/${gameId}/rankings`
}

export const getMyRankings = async (
  gameId: string,
  options?: RequestInit,
): Promise<getMyRankingsResponse> => {
  return fetcher<getMyRankingsResponse>(getGetMyRankingsUrl(gameId), {
    ...options,
    method: 'GET',
  })
}

export type getLeaderboardResponse200 = {
  data: LeaderboardEntry[]
  status: 200
}

export type getLeaderboardResponseSuccess = getLeaderboardResponse200 & {
  headers: Headers
}
export type getLeaderboardResponse = getLeaderboardResponseSuccess

export const getGetLeaderboardUrl = (gameId: string) => {
  return `/api/games/${gameId}/leaderboard`
}

export const getLeaderboard = async (
  gameId: string,
  options?: RequestInit,
): Promise<getLeaderboardResponse> => {
  return fetcher<getLeaderboardResponse>(getGetLeaderboardUrl(gameId), {
    ...options,
    method: 'GET',
  })
}

export type getWhatIfLeaderboardResponse200 = {
  data: LeaderboardEntry[]
  status: 200
}

export type getWhatIfLeaderboardResponseSuccess = getWhatIfLeaderboardResponse200 & {
  headers: Headers
}
export type getWhatIfLeaderboardResponse = getWhatIfLeaderboardResponseSuccess

export const getGetWhatIfLeaderboardUrl = (gameId: string, contestantId: string) => {
  return `/api/games/${gameId}/leaderboard/what-if/${contestantId}`
}

export const getWhatIfLeaderboard = async (
  gameId: string,
  contestantId: string,
  options?: RequestInit,
): Promise<getWhatIfLeaderboardResponse> => {
  return fetcher<getWhatIfLeaderboardResponse>(getGetWhatIfLeaderboardUrl(gameId, contestantId), {
    ...options,
    method: 'GET',
  })
}

export type grantAdminResponse200 = {
  data: MessageResponse
  status: 200
}

export type grantAdminResponseSuccess = grantAdminResponse200 & {
  headers: Headers
}
export type grantAdminResponse = grantAdminResponseSuccess

export const getGrantAdminUrl = (userId: string) => {
  return `/api/admin/users/${userId}/grant-admin`
}

export const grantAdmin = async (
  userId: string,
  options?: RequestInit,
): Promise<grantAdminResponse> => {
  return fetcher<grantAdminResponse>(getGrantAdminUrl(userId), {
    ...options,
    method: 'POST',
  })
}

export type listUsersResponse200 = {
  data: AdminUserResponse[]
  status: 200
}

export type listUsersResponseSuccess = listUsersResponse200 & {
  headers: Headers
}
export type listUsersResponse = listUsersResponseSuccess

export const getListUsersUrl = () => {
  return `/api/admin/users`
}

export const listUsers = async (options?: RequestInit): Promise<listUsersResponse> => {
  return fetcher<listUsersResponse>(getListUsersUrl(), {
    ...options,
    method: 'GET',
  })
}

export type getConfigResponse200 = {
  data: AppConfig
  status: 200
}

export type getConfigResponseSuccess = getConfigResponse200 & {
  headers: Headers
}
export type getConfigResponse = getConfigResponseSuccess

export const getGetConfigUrl = () => {
  return `/api/config`
}

export const getConfig = async (options?: RequestInit): Promise<getConfigResponse> => {
  return fetcher<getConfigResponse>(getGetConfigUrl(), {
    ...options,
    method: 'GET',
  })
}
