/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Mollenjagers API
 * OpenAPI spec version: v1
 */
import { fetcher } from './fetcher'
export interface Contestant {
  id?: string
  name?: string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  age?: number | string
  photoUrl?: string
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  eliminatedInEpisode?: number | string | null
}

export interface AddContestantsRequest {
  /** @nullable */
  contestants: Contestant[] | null
}

export interface AdminUserResponse {
  id: string
  email: string
  displayName: string
  isAdmin: boolean
}

export interface ContestantStats {
  contestantId: string
  name: string
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  avgRank: number | string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rankingCount: number | string
}

export interface CreateEpisodeRequest {
  deadline: string
  /** @nullable */
  eliminatedContestantIds: string[] | null
}

export interface CreateGameRequest {
  /** @nullable */
  name: string | null
  /** @nullable */
  contestants: Contestant[] | null
}

export interface Episode {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  number?: number | string
  deadline?: string
  /** @nullable */
  eliminatedContestantIds?: string[] | null
}

export interface EpisodeScore {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  episodeNumber?: number | string
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  score?: number | string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rankGiven?: number | string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalContestants?: number | string
}

export interface EpisodeStats {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  episodeNumber: number | string
  stats: ContestantStats[]
}

export interface ForgotPasswordRequest {
  email: string
}

export interface Game {
  id?: string
  name?: string
  adminUserId?: string
  contestants?: Contestant[]
  episodes?: Episode[]
  /** @nullable */
  moleContestantId?: string | null
  inviteCode?: string
}

export interface GameSummaryResponse {
  id: string
  name: string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  contestantCount: number | string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  episodeCount: number | string
}

export interface JoinGameRequest {
  /** @nullable */
  inviteCode: string | null
}

export interface LeaderboardEntry {
  userId?: string
  displayName?: string
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  totalScore?: number | string
  episodeScores?: EpisodeScore[]
}

export interface LoginRequest {
  email: string
  password: string
}

export interface Message {
  id?: string
  gameId?: string
  userId?: string
  displayName?: string
  content?: string
  postedAt?: string
}

export interface MessageResponse {
  message: string
}

export interface MessagesResponse {
  items: Message[]
  hasMore: boolean
}

export interface Player {
  id?: string
  gameId?: string
  userId?: string
  displayName?: string
  joinedAt?: string
}

export interface PlayerRankingResponse {
  userId: string
  displayName: string
  contestantIds: string[]
  submittedAt: string
}

export interface PostMessageRequest {
  /** @nullable */
  content: string | null
}

export interface Ranking {
  id?: string
  gameId?: string
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  episodeNumber?: number | string
  userId?: string
  contestantIds?: string[]
  submittedAt?: string
}

export interface RegisterRequest {
  email: string
  displayName: string
  password: string
  /** @nullable */
  inviteCode: string | null
}

export interface ResetPasswordRequest {
  token: string
  newPassword: string
}

export interface RevealMoleRequest {
  /** @nullable */
  moleContestantId: string | null
}

export interface RevealMoleResponse {
  message: string
  moleContestantId: string
}

export interface SubmitRankingRequest {
  /** @nullable */
  contestantIds: string[] | null
}

export interface UnreadCountResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  count: number | string
}

export interface UpdateEpisodeRequest {
  /** @nullable */
  deadline: string | null
  /** @nullable */
  eliminatedContestantIds: string[] | null
}

export interface UpdateProfileRequest {
  displayName: string
}

export interface UserInfo {
  userId: string
  displayName: string
  roles: string[]
}

export type GetMessagesParams = {
  /**
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  skip?: number | string
}

export type registerResponse200 = {
  data: UserInfo
  status: 200
}

export type registerResponseSuccess = registerResponse200 & {
  headers: Headers
}
export type registerResponse = registerResponseSuccess

export const getRegisterUrl = () => {
  return `/api/auth/register`
}

export const register = async (
  registerRequest: RegisterRequest,
  options?: RequestInit,
): Promise<registerResponse> => {
  return fetcher<registerResponse>(getRegisterUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerRequest),
  })
}

export type loginResponse200 = {
  data: UserInfo
  status: 200
}

export type loginResponseSuccess = loginResponse200 & {
  headers: Headers
}
export type loginResponse = loginResponseSuccess

export const getLoginUrl = () => {
  return `/api/auth/login`
}

export const login = async (
  loginRequest: LoginRequest,
  options?: RequestInit,
): Promise<loginResponse> => {
  return fetcher<loginResponse>(getLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest),
  })
}

export type forgotPasswordResponse200 = {
  data: MessageResponse
  status: 200
}

export type forgotPasswordResponseSuccess = forgotPasswordResponse200 & {
  headers: Headers
}
export type forgotPasswordResponse = forgotPasswordResponseSuccess

export const getForgotPasswordUrl = () => {
  return `/api/auth/forgot-password`
}

export const forgotPassword = async (
  forgotPasswordRequest: ForgotPasswordRequest,
  options?: RequestInit,
): Promise<forgotPasswordResponse> => {
  return fetcher<forgotPasswordResponse>(getForgotPasswordUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(forgotPasswordRequest),
  })
}

export type resetPasswordResponse200 = {
  data: UserInfo
  status: 200
}

export type resetPasswordResponseSuccess = resetPasswordResponse200 & {
  headers: Headers
}
export type resetPasswordResponse = resetPasswordResponseSuccess

export const getResetPasswordUrl = () => {
  return `/api/auth/reset-password`
}

export const resetPassword = async (
  resetPasswordRequest: ResetPasswordRequest,
  options?: RequestInit,
): Promise<resetPasswordResponse> => {
  return fetcher<resetPasswordResponse>(getResetPasswordUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(resetPasswordRequest),
  })
}

export type logoutResponse200 = {
  data: void
  status: 200
}

export type logoutResponseSuccess = logoutResponse200 & {
  headers: Headers
}
export type logoutResponse = logoutResponseSuccess

export const getLogoutUrl = () => {
  return `/api/auth/logout`
}

export const logout = async (options?: RequestInit): Promise<logoutResponse> => {
  return fetcher<logoutResponse>(getLogoutUrl(), {
    ...options,
    method: 'GET',
  })
}

export type getMeResponse200 = {
  data: UserInfo
  status: 200
}

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers
}
export type getMeResponse = getMeResponseSuccess

export const getGetMeUrl = () => {
  return `/api/me`
}

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return fetcher<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: 'GET',
  })
}

export interface UserPreferences {
  reminderEmailsEnabled: boolean
}

export interface UpdatePreferencesRequest {
  reminderEmailsEnabled: boolean
}

export type getPreferencesResponse200 = {
  data: UserPreferences
  status: 200
}

export type getPreferencesResponseSuccess = getPreferencesResponse200 & {
  headers: Headers
}
export type getPreferencesResponse = getPreferencesResponseSuccess

export const getGetPreferencesUrl = () => {
  return `/api/me/preferences`
}

export const getPreferences = async (options?: RequestInit): Promise<getPreferencesResponse> => {
  return fetcher<getPreferencesResponse>(getGetPreferencesUrl(), {
    ...options,
    method: 'GET',
  })
}

export type updatePreferencesResponse200 = {
  data: UserPreferences
  status: 200
}

export type updatePreferencesResponseSuccess = updatePreferencesResponse200 & {
  headers: Headers
}
export type updatePreferencesResponse = updatePreferencesResponseSuccess

export const getUpdatePreferencesUrl = () => {
  return `/api/me/preferences`
}

export const updatePreferences = async (
  updatePreferencesRequest: UpdatePreferencesRequest,
  options?: RequestInit,
): Promise<updatePreferencesResponse> => {
  return fetcher<updatePreferencesResponse>(getUpdatePreferencesUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePreferencesRequest),
  })
}

export type updateProfileResponse200 = {
  data: UserInfo
  status: 200
}

export type updateProfileResponseSuccess = updateProfileResponse200 & {
  headers: Headers
}
export type updateProfileResponse = updateProfileResponseSuccess

export const getUpdateProfileUrl = () => {
  return `/api/me`
}

export const updateProfile = async (
  updateProfileRequest: UpdateProfileRequest,
  options?: RequestInit,
): Promise<updateProfileResponse> => {
  return fetcher<updateProfileResponse>(getUpdateProfileUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProfileRequest),
  })
}

export type createGameResponse200 = {
  data: Game
  status: 200
}

export type createGameResponseSuccess = createGameResponse200 & {
  headers: Headers
}
export type createGameResponse = createGameResponseSuccess

export const getCreateGameUrl = () => {
  return `/api/games`
}

export const createGame = async (
  createGameRequest: CreateGameRequest,
  options?: RequestInit,
): Promise<createGameResponse> => {
  return fetcher<createGameResponse>(getCreateGameUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createGameRequest),
  })
}

export type getGameResponse200 = {
  data: Game
  status: 200
}

export type getGameResponseSuccess = getGameResponse200 & {
  headers: Headers
}
export type getGameResponse = getGameResponseSuccess

export const getGetGameUrl = (gameId: string) => {
  return `/api/games/${gameId}`
}

export const getGame = async (gameId: string, options?: RequestInit): Promise<getGameResponse> => {
  return fetcher<getGameResponse>(getGetGameUrl(gameId), {
    ...options,
    method: 'GET',
  })
}

export type deleteGameResponse204 = {
  data: void
  status: 204
}

export type deleteGameResponseSuccess = deleteGameResponse204 & {
  headers: Headers
}
export type deleteGameResponse = deleteGameResponseSuccess

export const getDeleteGameUrl = (gameId: string) => {
  return `/api/games/${gameId}`
}

export const deleteGame = async (
  gameId: string,
  options?: RequestInit,
): Promise<deleteGameResponse> => {
  return fetcher<deleteGameResponse>(getDeleteGameUrl(gameId), {
    ...options,
    method: 'DELETE',
  })
}

export type joinGameResponse200 = {
  data: MessageResponse
  status: 200
}

export type joinGameResponseSuccess = joinGameResponse200 & {
  headers: Headers
}
export type joinGameResponse = joinGameResponseSuccess

export const getJoinGameUrl = (gameId: string) => {
  return `/api/games/${gameId}/join`
}

export const joinGame = async (
  gameId: string,
  joinGameRequest: JoinGameRequest,
  options?: RequestInit,
): Promise<joinGameResponse> => {
  return fetcher<joinGameResponse>(getJoinGameUrl(gameId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(joinGameRequest),
  })
}

export type getGameByInviteResponse200 = {
  data: GameSummaryResponse
  status: 200
}

export type getGameByInviteResponseSuccess = getGameByInviteResponse200 & {
  headers: Headers
}
export type getGameByInviteResponse = getGameByInviteResponseSuccess

export const getGetGameByInviteUrl = (inviteCode: string) => {
  return `/api/games/by-invite/${inviteCode}`
}

export const getGameByInvite = async (
  inviteCode: string,
  options?: RequestInit,
): Promise<getGameByInviteResponse> => {
  return fetcher<getGameByInviteResponse>(getGetGameByInviteUrl(inviteCode), {
    ...options,
    method: 'GET',
  })
}

export type getMyGamesResponse200 = {
  data: Game[]
  status: 200
}

export type getMyGamesResponseSuccess = getMyGamesResponse200 & {
  headers: Headers
}
export type getMyGamesResponse = getMyGamesResponseSuccess

export const getGetMyGamesUrl = () => {
  return `/api/my-games`
}

export const getMyGames = async (options?: RequestInit): Promise<getMyGamesResponse> => {
  return fetcher<getMyGamesResponse>(getGetMyGamesUrl(), {
    ...options,
    method: 'GET',
  })
}

export type addContestantsResponse200 = {
  data: Game
  status: 200
}

export type addContestantsResponseSuccess = addContestantsResponse200 & {
  headers: Headers
}
export type addContestantsResponse = addContestantsResponseSuccess

export const getAddContestantsUrl = (gameId: string) => {
  return `/api/games/${gameId}/contestants`
}

export const addContestants = async (
  gameId: string,
  addContestantsRequest: AddContestantsRequest,
  options?: RequestInit,
): Promise<addContestantsResponse> => {
  return fetcher<addContestantsResponse>(getAddContestantsUrl(gameId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addContestantsRequest),
  })
}

export type createEpisodeResponse200 = {
  data: Episode
  status: 200
}

export type createEpisodeResponseSuccess = createEpisodeResponse200 & {
  headers: Headers
}
export type createEpisodeResponse = createEpisodeResponseSuccess

export const getCreateEpisodeUrl = (gameId: string) => {
  return `/api/games/${gameId}/episodes`
}

export const createEpisode = async (
  gameId: string,
  createEpisodeRequest: CreateEpisodeRequest,
  options?: RequestInit,
): Promise<createEpisodeResponse> => {
  return fetcher<createEpisodeResponse>(getCreateEpisodeUrl(gameId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createEpisodeRequest),
  })
}

export type updateEpisodeResponse200 = {
  data: Episode
  status: 200
}

export type updateEpisodeResponseSuccess = updateEpisodeResponse200 & {
  headers: Headers
}
export type updateEpisodeResponse = updateEpisodeResponseSuccess

export const getUpdateEpisodeUrl = (gameId: string, episodeNumber: number) => {
  return `/api/games/${gameId}/episodes/${episodeNumber}`
}

export const updateEpisode = async (
  gameId: string,
  episodeNumber: number,
  updateEpisodeRequest: UpdateEpisodeRequest,
  options?: RequestInit,
): Promise<updateEpisodeResponse> => {
  return fetcher<updateEpisodeResponse>(getUpdateEpisodeUrl(gameId, episodeNumber), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateEpisodeRequest),
  })
}

export type deleteEpisodeResponse204 = {
  data: void
  status: 204
}

export type deleteEpisodeResponseSuccess = deleteEpisodeResponse204 & {
  headers: Headers
}
export type deleteEpisodeResponse = deleteEpisodeResponseSuccess

export const getDeleteEpisodeUrl = (gameId: string, episodeNumber: number) => {
  return `/api/games/${gameId}/episodes/${episodeNumber}`
}

export const deleteEpisode = async (
  gameId: string,
  episodeNumber: number,
  options?: RequestInit,
): Promise<deleteEpisodeResponse> => {
  return fetcher<deleteEpisodeResponse>(getDeleteEpisodeUrl(gameId, episodeNumber), {
    ...options,
    method: 'DELETE',
  })
}

export type revealMoleResponse200 = {
  data: RevealMoleResponse
  status: 200
}

export type revealMoleResponseSuccess = revealMoleResponse200 & {
  headers: Headers
}
export type revealMoleResponse = revealMoleResponseSuccess

export const getRevealMoleUrl = (gameId: string) => {
  return `/api/games/${gameId}/reveal-mole`
}

export const revealMole = async (
  gameId: string,
  revealMoleRequest: RevealMoleRequest,
  options?: RequestInit,
): Promise<revealMoleResponse> => {
  return fetcher<revealMoleResponse>(getRevealMoleUrl(gameId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(revealMoleRequest),
  })
}

export type submitRankingResponse200 = {
  data: Ranking
  status: 200
}

export type submitRankingResponseSuccess = submitRankingResponse200 & {
  headers: Headers
}
export type submitRankingResponse = submitRankingResponseSuccess

export const getSubmitRankingUrl = (gameId: string, episodeNumber: number) => {
  return `/api/games/${gameId}/episodes/${episodeNumber}/rankings`
}

export const submitRanking = async (
  gameId: string,
  episodeNumber: number,
  submitRankingRequest: SubmitRankingRequest,
  options?: RequestInit,
): Promise<submitRankingResponse> => {
  return fetcher<submitRankingResponse>(getSubmitRankingUrl(gameId, episodeNumber), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(submitRankingRequest),
  })
}

export type getEpisodeRankingsResponse200 = {
  data: PlayerRankingResponse[]
  status: 200
}

export type getEpisodeRankingsResponseSuccess = getEpisodeRankingsResponse200 & {
  headers: Headers
}
export type getEpisodeRankingsResponse = getEpisodeRankingsResponseSuccess

export const getGetEpisodeRankingsUrl = (gameId: string, episodeNumber: number) => {
  return `/api/games/${gameId}/episodes/${episodeNumber}/rankings`
}

export const getEpisodeRankings = async (
  gameId: string,
  episodeNumber: number,
  options?: RequestInit,
): Promise<getEpisodeRankingsResponse> => {
  return fetcher<getEpisodeRankingsResponse>(getGetEpisodeRankingsUrl(gameId, episodeNumber), {
    ...options,
    method: 'GET',
  })
}

export type getMyRankingResponse200 = {
  data: Ranking
  status: 200
}

export type getMyRankingResponseSuccess = getMyRankingResponse200 & {
  headers: Headers
}
export type getMyRankingResponse = getMyRankingResponseSuccess

export const getGetMyRankingUrl = (gameId: string, episodeNumber: number) => {
  return `/api/games/${gameId}/episodes/${episodeNumber}/rankings/mine`
}

export const getMyRanking = async (
  gameId: string,
  episodeNumber: number,
  options?: RequestInit,
): Promise<getMyRankingResponse> => {
  return fetcher<getMyRankingResponse>(getGetMyRankingUrl(gameId, episodeNumber), {
    ...options,
    method: 'GET',
  })
}

export type getMyRankingsResponse200 = {
  data: Ranking[]
  status: 200
}

export type getMyRankingsResponseSuccess = getMyRankingsResponse200 & {
  headers: Headers
}
export type getMyRankingsResponse = getMyRankingsResponseSuccess

export const getGetMyRankingsUrl = (gameId: string) => {
  return `/api/games/${gameId}/rankings`
}

export const getMyRankings = async (
  gameId: string,
  options?: RequestInit,
): Promise<getMyRankingsResponse> => {
  return fetcher<getMyRankingsResponse>(getGetMyRankingsUrl(gameId), {
    ...options,
    method: 'GET',
  })
}

export type getLeaderboardResponse200 = {
  data: LeaderboardEntry[]
  status: 200
}

export type getLeaderboardResponseSuccess = getLeaderboardResponse200 & {
  headers: Headers
}
export type getLeaderboardResponse = getLeaderboardResponseSuccess

export const getGetLeaderboardUrl = (gameId: string) => {
  return `/api/games/${gameId}/leaderboard`
}

export const getLeaderboard = async (
  gameId: string,
  options?: RequestInit,
): Promise<getLeaderboardResponse> => {
  return fetcher<getLeaderboardResponse>(getGetLeaderboardUrl(gameId), {
    ...options,
    method: 'GET',
  })
}

export type getWhatIfLeaderboardResponse200 = {
  data: LeaderboardEntry[]
  status: 200
}

export type getWhatIfLeaderboardResponseSuccess = getWhatIfLeaderboardResponse200 & {
  headers: Headers
}
export type getWhatIfLeaderboardResponse = getWhatIfLeaderboardResponseSuccess

export const getGetWhatIfLeaderboardUrl = (gameId: string, contestantId: string) => {
  return `/api/games/${gameId}/leaderboard/what-if/${contestantId}`
}

export const getWhatIfLeaderboard = async (
  gameId: string,
  contestantId: string,
  options?: RequestInit,
): Promise<getWhatIfLeaderboardResponse> => {
  return fetcher<getWhatIfLeaderboardResponse>(getGetWhatIfLeaderboardUrl(gameId, contestantId), {
    ...options,
    method: 'GET',
  })
}

export type getMessagesResponse200 = {
  data: MessagesResponse
  status: 200
}

export type getMessagesResponseSuccess = getMessagesResponse200 & {
  headers: Headers
}
export type getMessagesResponse = getMessagesResponseSuccess

export const getGetMessagesUrl = (gameId: string, params?: GetMessagesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/games/${gameId}/messages?${stringifiedParams}`
    : `/api/games/${gameId}/messages`
}

export const getMessages = async (
  gameId: string,
  params?: GetMessagesParams,
  options?: RequestInit,
): Promise<getMessagesResponse> => {
  return fetcher<getMessagesResponse>(getGetMessagesUrl(gameId, params), {
    ...options,
    method: 'GET',
  })
}

export type postMessageResponse201 = {
  data: Message
  status: 201
}

export type postMessageResponseSuccess = postMessageResponse201 & {
  headers: Headers
}
export type postMessageResponse = postMessageResponseSuccess

export const getPostMessageUrl = (gameId: string) => {
  return `/api/games/${gameId}/messages`
}

export const postMessage = async (
  gameId: string,
  postMessageRequest: PostMessageRequest,
  options?: RequestInit,
): Promise<postMessageResponse> => {
  return fetcher<postMessageResponse>(getPostMessageUrl(gameId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postMessageRequest),
  })
}

export type getUnreadMessageCountResponse200 = {
  data: UnreadCountResponse
  status: 200
}

export type getUnreadMessageCountResponseSuccess = getUnreadMessageCountResponse200 & {
  headers: Headers
}
export type getUnreadMessageCountResponse = getUnreadMessageCountResponseSuccess

export const getGetUnreadMessageCountUrl = (gameId: string) => {
  return `/api/games/${gameId}/messages/unread-count`
}

export const getUnreadMessageCount = async (
  gameId: string,
  options?: RequestInit,
): Promise<getUnreadMessageCountResponse> => {
  return fetcher<getUnreadMessageCountResponse>(getGetUnreadMessageCountUrl(gameId), {
    ...options,
    method: 'GET',
  })
}

export type markMessagesReadResponse204 = {
  data: void
  status: 204
}

export type markMessagesReadResponseSuccess = markMessagesReadResponse204 & {
  headers: Headers
}
export type markMessagesReadResponse = markMessagesReadResponseSuccess

export const getMarkMessagesReadUrl = (gameId: string) => {
  return `/api/games/${gameId}/messages/mark-read`
}

export const markMessagesRead = async (
  gameId: string,
  options?: RequestInit,
): Promise<markMessagesReadResponse> => {
  return fetcher<markMessagesReadResponse>(getMarkMessagesReadUrl(gameId), {
    ...options,
    method: 'POST',
  })
}

export type getGamePlayersResponse200 = {
  data: Player[]
  status: 200
}

export type getGamePlayersResponseSuccess = getGamePlayersResponse200 & {
  headers: Headers
}
export type getGamePlayersResponse = getGamePlayersResponseSuccess

export const getGetGamePlayersUrl = (gameId: string) => {
  return `/api/games/${gameId}/players`
}

export const getGamePlayers = async (
  gameId: string,
  options?: RequestInit,
): Promise<getGamePlayersResponse> => {
  return fetcher<getGamePlayersResponse>(getGetGamePlayersUrl(gameId), {
    ...options,
    method: 'GET',
  })
}

export type getSuspectStatsResponse200 = {
  data: EpisodeStats[]
  status: 200
}

export type getSuspectStatsResponseSuccess = getSuspectStatsResponse200 & {
  headers: Headers
}
export type getSuspectStatsResponse = getSuspectStatsResponseSuccess

export const getGetSuspectStatsUrl = (gameId: string) => {
  return `/api/games/${gameId}/suspect-stats`
}

export const getSuspectStats = async (
  gameId: string,
  options?: RequestInit,
): Promise<getSuspectStatsResponse> => {
  return fetcher<getSuspectStatsResponse>(getGetSuspectStatsUrl(gameId), {
    ...options,
    method: 'GET',
  })
}

export type grantAdminResponse200 = {
  data: MessageResponse
  status: 200
}

export type grantAdminResponseSuccess = grantAdminResponse200 & {
  headers: Headers
}
export type grantAdminResponse = grantAdminResponseSuccess

export const getGrantAdminUrl = (userId: string) => {
  return `/api/admin/users/${userId}/grant-admin`
}

export const grantAdmin = async (
  userId: string,
  options?: RequestInit,
): Promise<grantAdminResponse> => {
  return fetcher<grantAdminResponse>(getGrantAdminUrl(userId), {
    ...options,
    method: 'POST',
  })
}

export type listUsersResponse200 = {
  data: AdminUserResponse[]
  status: 200
}

export type listUsersResponseSuccess = listUsersResponse200 & {
  headers: Headers
}
export type listUsersResponse = listUsersResponseSuccess

export const getListUsersUrl = () => {
  return `/api/admin/users`
}

export const listUsers = async (options?: RequestInit): Promise<listUsersResponse> => {
  return fetcher<listUsersResponse>(getListUsersUrl(), {
    ...options,
    method: 'GET',
  })
}
